services:
  - name: empirebot-zariah
    type: web
    env: python
    plan: free
    buildCommand: cd bots/zariah && pip install -r ../../requirements.txt
    startCommand: python zariah_pro.py
    envVars: []

  - name: empirebot-vendor
    type: web
    env: python
    plan: free
    buildCommand: cd bots/vendor && pip install -r ../../requirements.txt
    startCommand: python vendor_bot.py
    envVars: []

  - name: empirebot-trading
    type: web
    env: python
    plan: free
    buildCommand: cd bots/trading && pip install -r ../../requirements.txt
    startCommand: python trading_bot.py
    envVars: []

