services:
  - type: web
    name: empirebot-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    region: oregon

  - type: web
    name: empirebot-zariah
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn zariah_pro:app --host 0.0.0.0 --port 10001
    plan: free
    region: oregon

