services:
  - type: web
    name: empirebot-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bots.trading.trading_bot:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: BOT_TOKEN
        fromEnv: BOT_TOKEN
      - key: GOOGLE_CREDENTIALS
        fromEnv: GOOGLE_CREDENTIALS
