services:
  - type: web
    name: empirebot-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bots/bots/trading/trading_bot.py
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: BOT_TOKEN
        fromEnv: BOT_TOKEN
      - key: GOOGLE_CREDENTIALS
        fromEnv: GOOGLE_CREDENTIALS

